**Code For Rearranging order of Landmarks**

In [2]:
import os
import json
from copy import deepcopy

# -------------------------------------------------
# INPUT / OUTPUT
# -------------------------------------------------

input_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects"
output_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted"

os.makedirs(output_folder, exist_ok=True)

# -------------------------------------------------
# Landmark names in required order
# -------------------------------------------------

landmarks = [
    "Center of Femoral Head",
    "Femoral Head Fovea",
    "Greater Trochanter (Superior Tip)",
    "Greater Trochanter (Lateral Point)",
    "Lesser Trochanter",
    "Femoral Neck Center",
    "Medial Femoral Condyle",
    "Lateral Femoral Condyle",
    "Intercondylar Notch",
    "Medial Epicondyle",
    "Lateral Epicondyle"
]

# -------------------------------------------------
# Find all specimen numbers
# -------------------------------------------------

numbers = set()

for file in os.listdir(input_folder):
    if file.endswith(".mrk.json"):
        num = file.split("_")[-1].replace(".mrk.json", "")
        numbers.add(num)

numbers = sorted(numbers)

print(f"Found {len(numbers)} femurs")

# -------------------------------------------------
# Create one MRK file per femur
# -------------------------------------------------

for num in numbers:

    template = None
    control_points = []

    for idx, landmark in enumerate(landmarks, start=1):

        filename = f"{landmark}_{num}.mrk.json"
        filepath = os.path.join(input_folder, filename)

        if not os.path.exists(filepath):
            raise FileNotFoundError(filepath)

        with open(filepath, "r") as f:
            data = json.load(f)

        if template is None:
            template = deepcopy(data)

        cp = deepcopy(data["markups"][0]["controlPoints"][0])

        cp["id"] = str(idx)
        cp["label"] = landmark

        control_points.append(cp)

    template["markups"][0]["controlPoints"] = control_points
    template["markups"][0]["lastUsedControlPointNumber"] = 11

    out_path = os.path.join(output_folder, f"Landmarks_{num}.mrk.json")

    with open(out_path, "w") as f:
        json.dump(template, f, indent=4)

    print(f"Created Landmarks_{num}.mrk.json")

print("Finished!")

Found 15 femurs
Created Landmarks_01.mrk.json
Created Landmarks_02.mrk.json
Created Landmarks_03.mrk.json
Created Landmarks_05.mrk.json
Created Landmarks_13.mrk.json
Created Landmarks_14.mrk.json
Created Landmarks_19.mrk.json
Created Landmarks_21.mrk.json
Created Landmarks_22.mrk.json
Created Landmarks_26.mrk.json
Created Landmarks_27.mrk.json
Created Landmarks_29.mrk.json
Created Landmarks_30.mrk.json
Created Landmarks_31.mrk.json


FileNotFoundError: C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Center of Femoral Head_landmarks.mrk.json

**Used Rigid Transformation using Femur_21 As reference**

In [ ]:
import os
import json
import numpy as np
import trimesh
from copy import deepcopy

# ==========================================================
# FOLDER PATH
# ==========================================================

base_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted"

mesh_out_folder = os.path.join(
    base_folder,
    "rigid_aligned_meshes"
)

landmark_out_folder = os.path.join(
    base_folder,
    "rigid_aligned_landmarks"
)

os.makedirs(mesh_out_folder, exist_ok=True)
os.makedirs(landmark_out_folder, exist_ok=True)


# ==========================================================
# REFERENCE FEMUR
# ==========================================================

reference_num = 21

reference_landmark_file = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted\Landmarks_21.mrk.json"

reference_mesh_file = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted\Pat021.stl"


# ==========================================================
# READ LANDMARKS
# ==========================================================

def load_landmarks(filepath):

    with open(filepath, "r") as f:
        data = json.load(f)

    pts = []

    for cp in data["markups"][0]["controlPoints"]:
        pts.append(cp["position"])

    return np.array(pts, dtype=float), data


# ==========================================================
# KABSCH ALGORITHM
# ==========================================================

def rigid_transform(A, B):
    """
    Find R and t such that:

        B ≈ R @ A + t

    A = moving landmarks
    B = reference/fixed landmarks
    """

    centroid_A = A.mean(axis=0)
    centroid_B = B.mean(axis=0)

    AA = A - centroid_A
    BB = B - centroid_B

    H = AA.T @ BB

    U, S, Vt = np.linalg.svd(H)

    R = Vt.T @ U.T

    # Prevent reflection
    if np.linalg.det(R) < 0:

        Vt[2, :] *= -1

        R = Vt.T @ U.T

    t = centroid_B - R @ centroid_A

    return R, t


# ==========================================================
# CHECK REFERENCE FILES
# ==========================================================

if not os.path.exists(reference_landmark_file):

    raise FileNotFoundError(
        f"Reference landmark file not found:\n"
        f"{reference_landmark_file}"
    )

if not os.path.exists(reference_mesh_file):

    raise FileNotFoundError(
        f"Reference STL file not found:\n"
        f"{reference_mesh_file}"
    )


# ==========================================================
# LOAD REFERENCE LANDMARKS
# ==========================================================

reference_points, reference_json = load_landmarks(
    reference_landmark_file
)

print("==============================================")
print("REFERENCE FEMUR")
print("==============================================")

print(f"Reference femur : Pat{reference_num:03d}")
print(f"Landmarks       : {len(reference_points)}")

print("Reference points:")
print(reference_points)

print("==============================================\n")


# ==========================================================
# FIND ALL LANDMARK FILES
# ==========================================================

landmark_files = []

for filename in os.listdir(base_folder):

    if not filename.startswith("Landmarks_"):
        continue

    if not filename.endswith(".mrk.json"):
        continue

    # Example:
    # Landmarks_01.mrk.json

    number_part = filename[
        len("Landmarks_"):
        -len(".mrk.json")
    ]

    try:

        number = int(number_part)

        landmark_files.append(number)

    except ValueError:

        continue


# Remove duplicates and sort
femur_numbers = sorted(set(landmark_files))


print("Found femurs:")

for number in femur_numbers:
    print(f"  {number:02d}")

print(f"\nTotal femurs found: {len(femur_numbers)}")
print("==============================================\n")


# ==========================================================
# PROCESS ALL FEMURS
# ==========================================================

for number in femur_numbers:

    print("==============================================")
    print(f"Processing Femur {number:02d}")
    print("==============================================")

    # ------------------------------------------------------
    # File paths
    # ------------------------------------------------------

    mesh_file = os.path.join(
        base_folder,
        f"Pat{number:03d}.stl"
    )

    landmark_file = os.path.join(
        base_folder,
        f"Landmarks_{number:02d}.mrk.json"
    )

    # ------------------------------------------------------
    # Check files
    # ------------------------------------------------------

    if not os.path.exists(mesh_file):

        print(
            f"WARNING: STL not found:\n"
            f"{mesh_file}"
        )

        print("Skipping...\n")

        continue

    if not os.path.exists(landmark_file):

        print(
            f"WARNING: Landmark file not found:\n"
            f"{landmark_file}"
        )

        print("Skipping...\n")

        continue

    # ======================================================
    # REFERENCE FEMUR
    # ======================================================

    if number == reference_num:

        print("This is the reference femur.")

        # --------------------------------------------------
        # Copy mesh
        # --------------------------------------------------

        mesh = trimesh.load(
            mesh_file,
            process=False
        )

        output_mesh = os.path.join(
            mesh_out_folder,
            f"Aligned_femur_{number:02d}.stl"
        )

        mesh.export(output_mesh)

        # --------------------------------------------------
        # Copy landmarks
        # --------------------------------------------------

        with open(landmark_file, "r") as f:

            landmark_json = json.load(f)

        output_landmarks = os.path.join(
            landmark_out_folder,
            f"Aligned_FemurLandmarks_{number:02d}.mrk.json"
        )

        with open(output_landmarks, "w") as f:

            json.dump(
                landmark_json,
                f,
                indent=4
            )

        print("Reference mesh copied.")
        print("Reference landmarks copied.")
        print()

        continue

    # ======================================================
    # LOAD MOVING LANDMARKS
    # ======================================================

    moving_points, landmark_json = load_landmarks(
        landmark_file
    )

    print(
        f"Moving landmarks: "
        f"{len(moving_points)}"
    )

    # ------------------------------------------------------
    # Verify landmark count
    # ------------------------------------------------------

    if len(moving_points) != len(reference_points):

        print(
            f"ERROR: Landmark count mismatch!"
        )

        print(
            f"Reference: {len(reference_points)}"
        )

        print(
            f"Moving: {len(moving_points)}"
        )

        print("Skipping...\n")

        continue

    # ======================================================
    # COMPUTE RIGID TRANSFORMATION
    # ======================================================

    R, t = rigid_transform(
        moving_points,
        reference_points
    )

    # ======================================================
    # ROTATION ANGLE
    # ======================================================

    trace_R = np.trace(R)

    value = (trace_R - 1) / 2

    value = np.clip(
        value,
        -1.0,
        1.0
    )

    angle_deg = np.degrees(
        np.arccos(value)
    )

    print(
        f"Rotation angle: "
        f"{angle_deg:.2f} degrees"
    )

    # ======================================================
    # TRANSFORM STL MESH
    # ======================================================

    mesh = trimesh.load(
        mesh_file,
        process=False
    )

    vertices = mesh.vertices.copy()

    # Rigid transformation
    vertices = (
        R @ vertices.T
    ).T + t

    mesh.vertices = vertices

    # ------------------------------------------------------
    # Export aligned mesh
    # ------------------------------------------------------

    output_mesh = os.path.join(
        mesh_out_folder,
        f"Aligned_femur_{number:02d}.stl"
    )

    mesh.export(output_mesh)

    print(
        f"Saved mesh: "
        f"{output_mesh}"
    )

    # ======================================================
    # TRANSFORM LANDMARKS
    # ======================================================

    landmark_json_aligned = deepcopy(
        landmark_json
    )

    cps = (
        landmark_json_aligned[
            "markups"
        ][0][
            "controlPoints"
        ]
    )

    for cp in cps:

        p = np.array(
            cp["position"],
            dtype=float
        )

        p_new = (
            R @ p
        ) + t

        cp["position"] = (
            p_new.tolist()
        )

    # ======================================================
    # EXPORT ALIGNED LANDMARKS
    # ======================================================

    output_landmarks = os.path.join(
        landmark_out_folder,
        f"Aligned_FemurLandmarks_{number:02d}.mrk.json"
    )

    with open(
        output_landmarks,
        "w"
    ) as f:

        json.dump(
            landmark_json_aligned,
            f,
            indent=4
        )

    print(
        f"Saved landmarks: "
        f"{output_landmarks}"
    )

    print()


# ==========================================================
# FINISHED
# ==========================================================

print("\n==============================================")
print("RIGID ALIGNMENT COMPLETE")
print("==============================================")

print(
    f"Processed femurs: "
    f"{len(femur_numbers)}"
)

print(
    f"Aligned meshes saved to:\n"
    f"{mesh_out_folder}"
)

print(
    f"Aligned landmarks saved to:\n"
    f"{landmark_out_folder}"
)

print("==============================================")

REFERENCE FEMUR
Reference femur : Pat021
Landmarks       : 11
Reference points:
[[-103.704        13.649      -149.09364319]
 [ -91.35472107   14.30158234 -134.22257996]
 [-137.92570496   43.46266556 -154.14035034]
 [-163.73162842   22.87368965 -176.09397888]
 [-107.3928833    30.79389381 -196.88990784]
 [-120.084        18.441      -166.32038879]
 [ -62.94479752  -21.30088997 -505.50814819]
 [-131.09101868  -21.94809723 -501.75665283]
 [-102.5515976   -22.04574013 -508.77230835]
 [ -69.21523285   -9.32756519 -511.53735352]
 [-124.9981308    -9.61231232 -506.45523071]]

Found femurs:
  01
  02
  03
  05
  13
  14
  19
  21
  22
  26
  27
  29
  30
  31

Total femurs found: 14

Processing Femur 01
Moving landmarks: 11
Rotation angle: 11.04 degrees
Saved mesh: C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted\rigid_aligned_meshes\Aligned_femur_01.stl
Saved landmarks: C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Sub

**RBF Registration using method A**

In [27]:
import os
import json
import numpy as np
import trimesh

from scipy.interpolate import RBFInterpolator

In [28]:
landmark_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\11 landmarks\sorted_mrk\aligned_landmarks"

mesh_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\11 landmarks\sorted_mrk\aligned_meshes"

output_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\11 landmarks\sorted_mrk\rbf_registered_meshes_Method_A"

os.makedirs(output_folder, exist_ok=True)

In [29]:
def load_landmarks(filepath):

    with open(filepath, "r") as f:

        data = json.load(f)

    control_points = data["markups"][0]["controlPoints"]

    points = []

    for point in control_points:

        xyz = point["position"]

        points.append(xyz)

    points = np.array(points)

    return points

In [30]:
template_name = "16"

template_landmark_file = os.path.join(

    landmark_folder,

    "Aligned_FemurLandmarks_" + template_name + ".mrk.json"
)

template_mesh_file = os.path.join(

    mesh_folder,

    "Aligned_femur_" + template_name + ".stl"
)

template_landmarks = load_landmarks(

    template_landmark_file
)

template_mesh = trimesh.load(

        
)

print(template_landmarks.shape)
print(template_mesh.vertices.shape)

TypeError: load() missing 1 required positional argument: 'file_obj'

In [ ]:
all_landmark_files = os.listdir(landmark_folder)

for landmark_file in all_landmark_files:

    if not landmark_file.endswith(".mrk.json"):

        continue


    # Skip template itself

    if landmark_file == "Aligned_FemurLandmarks_16.mrk.json":

        continue


    print()
    print("----------------------------------")
    print("Processing :", landmark_file)


    # ---------- Load source landmarks ----------

    source_landmark_path = os.path.join(

        landmark_folder,

        landmark_file
    )

    source_landmarks = load_landmarks(

        source_landmark_path
    )


    # ---------- Extract femur number ----------

    femur_number = landmark_file[-11:-9]


    # Example:
    # Aligned_FemurLandmarks_01.mrk.json
    #
    # becomes
    #
    # 01


    mesh_name = "Aligned_femur_" + femur_number + ".stl"

    source_mesh_path = os.path.join(

        mesh_folder,

        mesh_name
    )


    # ---------- Load source mesh ----------

    source_mesh = trimesh.load(

        source_mesh_path
    )

    source_vertices = source_mesh.vertices


    # ---------- Compute displacement ----------

    displacement = (

        template_landmarks

        -

        source_landmarks
    )


    # ---------- Create RBF ----------

    rbf = RBFInterpolator(

        source_landmarks,

        displacement,

        kernel="linear"
    )


    # ---------- Warp vertices ----------

    warped_vertices = (

        source_vertices

        +

        rbf(source_vertices)
    )


    # ---------- Create warped mesh ----------

    warped_mesh = trimesh.Trimesh(

        vertices=warped_vertices,

        faces=source_mesh.faces
    )


    # ---------- Save ----------

    output_name = (

        "RBF_Aligned_femur_"

        +

        femur_number

        +

        ".stl"
    )

    output_path = os.path.join(

        output_folder,

        output_name
    )


    warped_mesh.export(

        output_path
    )


    print("Saved :", output_name)

    print("Vertices :", source_vertices.shape)


----------------------------------
Processing : Aligned_FemurLandmarks_01.mrk.json
Saved : RBF_Aligned_femur_01.stl
Vertices : (22903, 3)

----------------------------------
Processing : Aligned_FemurLandmarks_02.mrk.json
Saved : RBF_Aligned_femur_02.stl
Vertices : (38588, 3)

----------------------------------
Processing : Aligned_FemurLandmarks_03.mrk.json
Saved : RBF_Aligned_femur_03.stl
Vertices : (24580, 3)

----------------------------------
Processing : Aligned_FemurLandmarks_04.mrk.json
Saved : RBF_Aligned_femur_04.stl
Vertices : (17871, 3)

----------------------------------
Processing : Aligned_FemurLandmarks_05.mrk.json
Saved : RBF_Aligned_femur_05.stl
Vertices : (25958, 3)

----------------------------------
Processing : Aligned_FemurLandmarks_06.mrk.json
Saved : RBF_Aligned_femur_06.stl
Vertices : (26975, 3)

----------------------------------
Processing : Aligned_FemurLandmarks_07.mrk.json
Saved : RBF_Aligned_femur_07.stl
Vertices : (30506, 3)

--------------------------

***Nearest-Neighbor Correspondence***

In [ ]:
import os
import trimesh
import numpy as np

from scipy.spatial import cKDTree

In [ ]:
template_mesh_path = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\11 landmarks\sorted_mrk\rigid_aligned_meshes\Aligned_femur_16"

rbf_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\11 landmarks\sorted_mrk\rbf_registered_meshes_Method_A"

output_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\11 landmarks\sorted_mrk\correspondence_meshes"

os.makedirs(output_folder, exist_ok=True)

In [ ]:
template_mesh = trimesh.load(template_mesh_path) #femur_16

template_vertices = template_mesh.vertices

template_faces = template_mesh.faces

print(template_vertices.shape)
print(template_faces.shape)

ValueError: string is not a file: `C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\11 landmarks\sorted_mrk\rigid_aligned_meshes\Aligned_femur_16`

In [ ]:
all_rbf_meshes = os.listdir(rbf_folder)

print(all_rbf_meshes)

['RBF_Aligned_femur_01.stl', 'RBF_Aligned_femur_02.stl', 'RBF_Aligned_femur_03.stl', 'RBF_Aligned_femur_04.stl', 'RBF_Aligned_femur_05.stl', 'RBF_Aligned_femur_06.stl', 'RBF_Aligned_femur_07.stl', 'RBF_Aligned_femur_08.stl', 'RBF_Aligned_femur_09.stl', 'RBF_Aligned_femur_10.stl', 'RBF_Aligned_femur_11.stl', 'RBF_Aligned_femur_12.stl', 'RBF_Aligned_femur_13.stl', 'RBF_Aligned_femur_14.stl', 'RBF_Aligned_femur_15.stl', 'RBF_Aligned_femur_17.stl']


In [ ]:
for mesh_file in all_rbf_meshes:

    if not mesh_file.endswith(".stl"):
        continue

    print()
    print("Processing :", mesh_file)


    # ------------------------
    # Load RBF mesh
    # ------------------------

    mesh_path = os.path.join(
        rbf_folder,
        mesh_file
    )

    warped_mesh = trimesh.load(
        mesh_path
    )

    warped_vertices = warped_mesh.vertices


    # ------------------------
    # Build KD Tree
    # ------------------------

    tree = cKDTree(
        warped_vertices
    )


    # ------------------------
    # Find nearest neighbor
    # for every template vertex
    # ------------------------

    distances, indices = tree.query(
        template_vertices
    )


    # ------------------------
    # Get corresponding points
    # ------------------------

    new_vertices = warped_vertices[
        indices
    ]


    # ------------------------
    # Create mesh
    # ------------------------

    new_mesh = trimesh.Trimesh(

        vertices=new_vertices,

        faces=template_faces
    )


    # ------------------------
    # Save
    # ------------------------

    output_name = "Correspondence_" + mesh_file

    output_path = os.path.join(
        output_folder,
        output_name
    )

    new_mesh.export(
        output_path
    )


    print("Saved :", output_name)
    print(warped_mesh.vertices)
    print(new_vertices.shape)


Processing : RBF_Aligned_femur_01.stl


ValueError: string is not a file: `C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\11 landmarks\sorted_mrk\rbf_registered_meshes\RBF_Aligned_femur_01.stl`

In [ ]:
mesh = trimesh.load(
    r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\11 landmarks\sorted_mrk\correspondence_meshes\Correspondence_RBF_Aligned_femur_14.stl"
)

print(mesh.vertices.shape)

(20027, 3)


**Method B**

In [1]:
import os
import json
import numpy as np
import trimesh

from scipy.interpolate import RBFInterpolator

In [2]:
landmark_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted\rigid_aligned_landmarks"

mesh_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted\rigid_aligned_meshes"

output_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted\rbf_registered_meshes_Method_B"

os.makedirs(output_folder, exist_ok=True)

In [3]:
def load_landmarks(filepath):

    with open(filepath, "r") as f:
        data = json.load(f)

    control_points = data["markups"][0]["controlPoints"]

    points = []

    for point in control_points:

        points.append(point["position"])

    return np.array(points)

In [33]:
import os
import trimesh
import numpy as np

# ==========================================================
# FOLDER CONTAINING ALIGNED STL FILES
# ==========================================================

mesh_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted\rigid_aligned_meshes"

# ==========================================================
# FIND ALL STL FILES
# ==========================================================

stl_files = sorted(
    [
        f for f in os.listdir(mesh_folder)
        if f.lower().endswith(".stl")
    ]
)

print(f"Found {len(stl_files)} STL files")
print("=" * 60)

# ==========================================================
# LOAD ALL MESHES AND CHECK VERTICES
# ==========================================================

all_vertices = {}

for filename in stl_files:

    filepath = os.path.join(mesh_folder, filename)

    mesh = trimesh.load(
        filepath,
        process=False
    )

    vertices = np.asarray(mesh.vertices)
    faces = np.asarray(mesh.faces)

    all_vertices[filename] = vertices

    print(f"{filename}")
    print(f"    Vertices : {vertices.shape}")
    print(f"    Faces    : {faces.shape}")

print("=" * 60)
print("Finished loading all meshes.")

Found 14 STL files
Aligned_femur_01.stl
    Vertices : (429048, 3)
    Faces    : (143016, 3)
Aligned_femur_02.stl
    Vertices : (473052, 3)
    Faces    : (157684, 3)
Aligned_femur_03.stl
    Vertices : (396960, 3)
    Faces    : (132320, 3)
Aligned_femur_05.stl
    Vertices : (490992, 3)
    Faces    : (163664, 3)
Aligned_femur_13.stl
    Vertices : (387132, 3)
    Faces    : (129044, 3)
Aligned_femur_14.stl
    Vertices : (489804, 3)
    Faces    : (163268, 3)
Aligned_femur_19.stl
    Vertices : (350832, 3)
    Faces    : (116944, 3)
Aligned_femur_21.stl
    Vertices : (636888, 3)
    Faces    : (212296, 3)
Aligned_femur_22.stl
    Vertices : (496848, 3)
    Faces    : (165616, 3)
Aligned_femur_26.stl
    Vertices : (469932, 3)
    Faces    : (156644, 3)
Aligned_femur_27.stl
    Vertices : (411024, 3)
    Faces    : (137008, 3)
Aligned_femur_29.stl
    Vertices : (402000, 3)
    Faces    : (134000, 3)
Aligned_femur_30.stl
    Vertices : (651084, 3)
    Faces    : (217028, 3)
Aligne

In [5]:
template_name = "02"

template_mesh_path = os.path.join(
    mesh_folder,
    "Aligned_femur_" + template_name + ".stl"
)

template_landmark_path = os.path.join(
    landmark_folder,
    "Aligned_FemurLandmarks_" + template_name + ".mrk.json"
)

template_mesh = trimesh.load(template_mesh_path)

template_vertices = template_mesh.vertices

template_faces = template_mesh.faces

template_landmarks = load_landmarks(
    template_landmark_path
)

print(template_vertices.shape)
print(template_landmarks.shape)

(78844, 3)
(11, 3)


In [6]:
all_landmark_files = os.listdir(
    landmark_folder
)

for landmark_file in all_landmark_files:

    if not landmark_file.endswith(".mrk.json"):
        continue

    if landmark_file == "Aligned_FemurLandmarks_02.mrk.json":
        continue


    print()
    print("Processing :", landmark_file)


    # --------------------------------
    # Extract femur number
    # --------------------------------

    femur_number = landmark_file[-11:-9]


    # --------------------------------
    # Load subject landmarks
    # --------------------------------

    subject_landmark_path = os.path.join(
        landmark_folder,
        landmark_file
    )

    subject_landmarks = load_landmarks(
        subject_landmark_path
    )


    # --------------------------------
    # Landmark displacement
    # --------------------------------

    displacement = (
        subject_landmarks
        -
        template_landmarks
    )


    # --------------------------------
    # Build RBF
    # --------------------------------

    rbf = RBFInterpolator(

        template_landmarks,

        displacement,

        kernel="linear"
    )


    # --------------------------------
    # Warp TEMPLATE vertices
    # --------------------------------

    warped_vertices = (
        template_vertices
        +
        rbf(template_vertices)
    )


    # --------------------------------
    # Create mesh
    # --------------------------------

    warped_mesh = trimesh.Trimesh(

        vertices=warped_vertices,

        faces=template_faces
    )


    # --------------------------------
    # Save
    # --------------------------------

    output_name = (
        "rbf_femur_"
        +
        femur_number
        +
        ".stl"
    )

    output_path = os.path.join(
        output_folder,
        output_name
    )

    warped_mesh.export(
        output_path
    )

    print("Saved :", output_name)


Processing : Aligned_FemurLandmarks_01.mrk.json
Saved : rbf_femur_01.stl

Processing : Aligned_FemurLandmarks_03.mrk.json
Saved : rbf_femur_03.stl

Processing : Aligned_FemurLandmarks_05.mrk.json
Saved : rbf_femur_05.stl

Processing : Aligned_FemurLandmarks_13.mrk.json
Saved : rbf_femur_13.stl

Processing : Aligned_FemurLandmarks_14.mrk.json
Saved : rbf_femur_14.stl

Processing : Aligned_FemurLandmarks_19.mrk.json
Saved : rbf_femur_19.stl

Processing : Aligned_FemurLandmarks_21.mrk.json
Saved : rbf_femur_21.stl

Processing : Aligned_FemurLandmarks_22.mrk.json
Saved : rbf_femur_22.stl

Processing : Aligned_FemurLandmarks_26.mrk.json
Saved : rbf_femur_26.stl

Processing : Aligned_FemurLandmarks_27.mrk.json
Saved : rbf_femur_27.stl

Processing : Aligned_FemurLandmarks_29.mrk.json
Saved : rbf_femur_29.stl

Processing : Aligned_FemurLandmarks_30.mrk.json
Saved : rbf_femur_30.stl

Processing : Aligned_FemurLandmarks_31.mrk.json
Saved : rbf_femur_31.stl


In [7]:
template_vertices.shape

(78844, 3)

**Check for rbf working**

In [9]:
mesh = trimesh.load(
    r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted\rbf_registered_meshes_Method_B\rbf_femur_01.stl"
)

print(mesh.vertices.shape)
print(mesh.faces.shape)

(78844, 3)
(157684, 3)


**PCA**

In [10]:
import os
import trimesh
import numpy as np

In [11]:
mesh_folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Subjects\Subjects_sorted\rbf_registered_meshes_Method_B"

In [12]:
import os

shape_matrix = []

all_meshes = os.listdir(mesh_folder)

for file in all_meshes:

    if not file.endswith(".stl"):
        continue

    mesh_path = os.path.join(
        mesh_folder,
        file
    )

    mesh = trimesh.load(mesh_path)

    vertices = mesh.vertices

    vector = vertices.flatten()

    shape_matrix.append(vector)

In [13]:
shape_matrix = np.array(shape_matrix)

print(shape_matrix.shape)

(13, 236532)


In [14]:
shape_matrix

array([[-129.21981812,  -50.33217621, -524.81427002, ..., -100.00634003,
          20.8227272 , -137.64367676],
       [-129.06561279,  -47.60910797, -529.32147217, ...,  -97.00873566,
          25.89444733, -139.71638489],
       [-129.62792969,  -50.88807678, -558.23425293, ..., -100.32933807,
          30.5710125 , -106.39885712],
       ...,
       [-127.31945038,  -51.27557755, -539.51629639, ..., -100.25376892,
          24.41607666, -125.68856049],
       [-124.54200745,  -53.56257248, -542.57965088, ..., -136.51983643,
          26.02410889, -142.448349  ],
       [-126.81627655,  -49.8868103 , -536.53546143, ...,  -99.80531311,
          25.29628372, -129.4524231 ]], shape=(13, 236532))

In [15]:
mean_shape = np.mean(
    shape_matrix,
    axis=0
)

print(mean_shape.shape)

(236532,)


In [16]:
shape_matrix

array([[-129.21981812,  -50.33217621, -524.81427002, ..., -100.00634003,
          20.8227272 , -137.64367676],
       [-129.06561279,  -47.60910797, -529.32147217, ...,  -97.00873566,
          25.89444733, -139.71638489],
       [-129.62792969,  -50.88807678, -558.23425293, ..., -100.32933807,
          30.5710125 , -106.39885712],
       ...,
       [-127.31945038,  -51.27557755, -539.51629639, ..., -100.25376892,
          24.41607666, -125.68856049],
       [-124.54200745,  -53.56257248, -542.57965088, ..., -136.51983643,
          26.02410889, -142.448349  ],
       [-126.81627655,  -49.8868103 , -536.53546143, ...,  -99.80531311,
          25.29628372, -129.4524231 ]], shape=(13, 236532))

In [17]:
mean_shape  

array([-127.5135545 ,  -50.3564949 , -534.07888559, ..., -103.41619286,
         24.9043987 , -131.77908795], shape=(236532,))

In [18]:
centered_data = (
    shape_matrix
    -
    mean_shape
)

In [19]:
centered_data

array([[-1.70626362e+00,  2.43186951e-02,  9.26461557e+00, ...,
         3.40985283e+00, -4.08167149e+00, -5.86458881e+00],
       [-1.55205829e+00,  2.74738693e+00,  4.75741342e+00, ...,
         6.40745720e+00,  9.90048629e-01, -7.93729694e+00],
       [-2.11437519e+00, -5.31581879e-01, -2.41553673e+01, ...,
         3.08685479e+00,  5.66661380e+00,  2.53802308e+01],
       ...,
       [ 1.94104121e-01, -9.19082642e-01, -5.43741079e+00, ...,
         3.16242394e+00, -4.88322038e-01,  6.09052746e+00],
       [ 2.97154705e+00, -3.20607758e+00, -8.50076529e+00, ...,
        -3.31036436e+01,  1.11971019e+00, -1.06692611e+01],
       [ 6.97277949e-01,  4.69684601e-01, -2.45657583e+00, ...,
         3.61087975e+00,  3.91885024e-01,  2.32666485e+00]],
      shape=(13, 236532))

In [20]:
from sklearn.decomposition import PCA

pca = PCA()

pca.fit(centered_data)

,"n_components n_components: int, float or 'mle', default=NoneNumber of components to keep.if n_components is not set all components are kept:: n_components == min(n_samples, n_features)If ``n_components == 'mle'`` and ``svd_solver == 'full'``, Minka'sMLE is used to guess the dimension. Use of ``n_components == 'mle'``will interpret ``svd_solver == 'auto'`` as ``svd_solver == 'full'``.If ``0 < n_components < 1`` and ``svd_solver == 'full'``, select thenumber of components such that the amount of variance that needs to beexplained is greater than the percentage specified by n_components.If ``svd_solver == 'arpack'``, the number of components must bestrictly less than the minimum of n_features and n_samples.Hence, the None case results in:: n_components == min(n_samples, n_features) - 1",None
,"copy copy: bool, default=TrueIf False, data passed to fit are overwritten and runningfit(X).transform(X) will not yield the expected results,use fit_transform(X) instead.",True
,"whiten whiten: bool, default=FalseWhen True (False by default) the `components_` vectors are multipliedby the square root of n_samples and then divided by the singular valuesto ensure uncorrelated outputs with unit component-wise variances.Whitening will remove some information from the transformed signal(the relative variance scales of the components) but can sometimeimprove the predictive accuracy of the downstream estimators bymaking their data respect some hard-wired assumptions.",False
,"svd_solver svd_solver: {'auto', 'full', 'covariance_eigh', 'arpack', 'randomized'}, default='auto'""auto"" : The solver is selected by a default 'auto' policy is based on `X.shape` and `n_components`: if the input data has fewer than 1000 features and more than 10 times as many samples, then the ""covariance_eigh"" solver is used. Otherwise, if the input data is larger than 500x500 and the number of components to extract is lower than 80% of the smallest dimension of the data, then the more efficient ""randomized"" method is selected. Otherwise the exact ""full"" SVD is computed and optionally truncated afterwards.""full"" : Run exact full SVD calling the standard LAPACK solver via `scipy.linalg.svd` and select the components by postprocessing""covariance_eigh"" : Precompute the covariance matrix (on centered data), run a classical eigenvalue decomposition on the covariance matrix typically using LAPACK and select the components by postprocessing. This solver is very efficient for n_samples >> n_features and small n_features. It is, however, not tractable otherwise for large n_features (large memory footprint required to materialize the covariance matrix). Also note that compared to the ""full"" solver, this solver effectively doubles the condition number and is therefore less numerical stable (e.g. on input data with a large range of singular values).""arpack"" : Run SVD truncated to `n_components` calling ARPACK solver via `scipy.sparse.linalg.svds`. It requires strictly `0 < n_components < min(X.shape)`""randomized"" : Run randomized SVD by the method of Halko et al... versionadded:: 0.18.0.. versionchanged:: 1.5 Added the 'covariance_eigh' solver.",'auto'
,"tol tol: float, default=0.0Tolerance for singular values computed by svd_solver == 'arpack'.Must be of range [0.0, infinity)... versionadded:: 0.18.0",0.0
,"iterated_power iterated_power: int or 'auto', default='auto'Number of iterations for the power method computed bysvd_solver == 'randomized'.Must be of range [0, infinity)... versionadded:: 0.18.0",'auto'
,"n_oversamples n_oversamples: int, default=10This parameter is only relevant when `svd_solver=""randomized""`.It corresponds to the additional number of random vectors to sample therange of `X` so as to ensure proper conditioning. See:func:`~sklearn.utils.extmath.randomized_svd` for more details... versionadded:: 1.1",10
,"power_iteration_normalizer power_iteration_normalizer: {'auto', 'QR', 'LU', 'none'}, default='auto'Power iteration normalizer for randomized S

**Cumulative explained variance ratio**
(#How much of the total shape variation have I captured?)

In [21]:
variance_ratio = pca.explained_variance_ratio_

cumulative_variance = np.cumsum(
    variance_ratio
)

print(cumulative_variance)

[0.69195363 0.92616581 0.96562677 0.97924783 0.99005717 0.99434824
 0.99623223 0.99755819 0.99856372 0.99942008 0.99974947 1.
 1.        ]


In [22]:
print(shape_matrix.shape)
print(centered_data.shape)

(13, 236532)
(13, 236532)


**(Eigen Vectors)**

In [23]:
print(pca.components_)

[[ 1.32353431e-04  6.30770351e-04  4.28842537e-03 ...  1.90275205e-03
  -6.98131566e-04 -3.72445778e-03]
 [-5.47537638e-04  1.54661714e-04 -1.78049809e-03 ...  4.91810536e-03
   2.91487489e-04  4.86343732e-03]
 [-2.79847249e-03 -6.39445349e-04  2.28610499e-04 ... -4.21395246e-04
  -2.70717343e-04  1.89964223e-03]
 ...
 [-3.16470425e-04 -4.71503207e-04  1.52922163e-03 ...  6.60403930e-04
   2.66331441e-03 -1.48433886e-03]
 [ 2.03568460e-03 -5.21951291e-04 -7.99731541e-04 ... -1.21294801e-03
   1.45311089e-03  5.97125978e-04]
 [ 7.49534443e-01 -4.10849342e-02 -3.83218404e-01 ... -5.49259319e-05
   2.31000920e-05  2.40865613e-04]]


**Eigenvalues That Help Compute σ and normalize scores (lambda values)**

In [24]:
print(pca.explained_variance_)

[8.91040147e+06 3.01598913e+06 5.08145303e+05 1.75400641e+05
 1.39193646e+05 5.52568731e+04 2.42604665e+04 1.70745709e+04
 1.29483439e+04 1.10274489e+04 4.24172090e+03 3.22606156e+03
 5.39734630e-24]


**Finding p-values for all the femurs in the dataset using PCA**

In [25]:
scores=pca.transform(centered_data)
scores

array([[ 2.22251173e+03,  2.35853720e+02,  5.38193427e+02,
        -6.70161640e+02,  4.03405161e+02, -4.00018103e+02,
         7.40745066e+01, -1.63306236e+02,  2.53493807e+01,
         1.92225709e+00, -3.40579595e+01, -6.21447996e+01,
        -2.04825929e-11],
       [ 1.48823415e+03,  2.27318224e+02,  1.15984860e+01,
         6.43036810e+02,  4.44480296e+01, -3.76912486e+02,
         3.67599271e+01, -9.58363125e+01, -9.10131606e+01,
        -3.83928844e+01,  6.64780099e+01,  1.05643441e+02,
         1.39455299e-12],
       [-4.59755937e+03,  2.12869883e+03, -5.43657553e+02,
         3.50499056e+02,  3.28207669e+00, -2.47534183e+02,
        -1.37835364e+02,  6.52567977e+01,  2.01231203e+02,
        -3.73106447e+01, -4.95091529e+00, -4.09328812e+01,
         2.01869609e-12],
       [ 3.52205226e+03,  1.67628527e+02, -2.05658100e+03,
        -3.62590272e+02, -2.47955131e+02,  6.75001058e+01,
         3.17509041e+01, -2.03944832e+01, -6.58069832e+00,
        -5.88157243e+00,  2.46146422e

In [26]:
scores.shape

(13, 13)

**Normalizing p-values**

In [27]:
scores_5 = scores[:,:5]
scores_all=scores[:,:16]
std = np.sqrt(pca.explained_variance_[:5]) 
std_all = np.sqrt(pca.explained_variance_[:16]) 

normalized_scores_5 = scores_5/std #pi​=​scorei/sqt(λi​)​​
normalized_scores_all = scores_all/std_all

In [28]:
normalized_scores_5

array([[ 0.74455267,  0.13580878,  0.75499562, -1.60016209,  1.081264  ],
       [ 0.49856597,  0.13089389,  0.01627074,  1.53539544,  0.11913594],
       [-1.54020564,  1.22574275, -0.76266088,  0.83689556,  0.00879709],
       [ 1.17990532,  0.0965235 , -2.88504016, -0.86576607, -0.66460468],
       [-0.11999988,  0.15192081,  0.26579212,  0.62908511,  0.18674187],
       [ 1.9069314 , -0.66913384,  0.70048774,  1.09052796, -0.6315651 ],
       [ 0.08950917,  0.09638694,  0.18768748,  0.73989247,  0.16612891],
       [-1.28783613,  0.73288155,  0.43698046, -0.84630122, -1.77272186],
       [-0.11807258,  0.49812515, -0.05721588, -0.77578727,  2.24337722],
       [ 0.35357468, -0.15030339,  1.18650318, -1.3880372 , -1.17013792],
       [-0.30795581,  0.42661761,  0.22966152,  0.31563312,  0.48504872],
       [-1.37141904, -2.98145621, -0.40455928, -0.06076207,  0.2316089 ],
       [-0.02755012,  0.30599245,  0.33109733,  0.38938626, -0.28307309]])

**Creating a csv file containing p-values for all the femurs in the dataset**

In [29]:
import pandas as pd

df = pd.DataFrame(
{
    "image_name":[
        "Femur_01.png",
        "Femur_03.png",
        "Femur_05.png",
        "Femur_13.png",
        "Femur_14.png",
        "Femur_19.png",
        "Femur_21.png",
        "Femur_22.png",
        "Femur_26.png",
        "Femur_27.png",
        "Femur_29.png",
        "Femur_30.png",
        "Femur_31.png",
    ],

    "p1":normalized_scores_5[:,0],
    "p2":normalized_scores_5[:,1],
    "p3":normalized_scores_5[:,2],
    "p4":normalized_scores_5[:,3],
    "p5":normalized_scores_5[:,4]
}
)

df.to_csv(
    "gt_p-values_labels.csv",
    index=False
)

In [30]:
import pandas as pd
df=pd.read_csv('gt_p-values_labels.csv')
print(df)

      image_name        p1        p2        p3        p4        p5
0   Femur_01.png  0.744553  0.135809  0.754996 -1.600162  1.081264
1   Femur_03.png  0.498566  0.130894  0.016271  1.535395  0.119136
2   Femur_05.png -1.540206  1.225743 -0.762661  0.836896  0.008797
3   Femur_13.png  1.179905  0.096523 -2.885040 -0.865766 -0.664605
4   Femur_14.png -0.120000  0.151921  0.265792  0.629085  0.186742
5   Femur_19.png  1.906931 -0.669134  0.700488  1.090528 -0.631565
6   Femur_21.png  0.089509  0.096387  0.187687  0.739892  0.166129
7   Femur_22.png -1.287836  0.732882  0.436980 -0.846301 -1.772722
8   Femur_26.png -0.118073  0.498125 -0.057216 -0.775787  2.243377
9   Femur_27.png  0.353575 -0.150303  1.186503 -1.388037 -1.170138
10  Femur_29.png -0.307956  0.426618  0.229662  0.315633  0.485049
11  Femur_30.png -1.371419 -2.981456 -0.404559 -0.060762  0.231609
12  Femur_31.png -0.027550  0.305992  0.331097  0.389386 -0.283073


In [31]:
template_mesh.faces

TrackedArray([[    0,     1,     2],
              [    0,     3,     4],
              [    1,     0,     4],
              ...,
              [78194, 78192, 78842],
              [78843, 78194, 78842],
              [78165, 78194, 78843]], shape=(157684, 3))

In [32]:
eigenvectors = pca.components_[:5]

eigenvalues = pca.explained_variance_[:5]

sigma = np.sqrt(eigenvalues)

In [33]:
mean_vertices = mean_shape.reshape(-1,3)

In [34]:
mode1 = eigenvectors[0].reshape(-1,3)

sigma1 = sigma[0]

mode2 = eigenvectors[1].reshape(-1,3)

sigma2 = sigma[1]

mode3 = eigenvectors[2].reshape(-1,3)

sigma3 = sigma[2]

mode4 = eigenvectors[3].reshape(-1,3)

sigma4 = sigma[3]

mode5 = eigenvectors[4].reshape(-1,3)

sigma5 = sigma[4]

In [35]:
import os
import trimesh

# Create output folder
output_folder = "Visualization_of_p_values"
os.makedirs(output_folder, exist_ok=True)

# Mean mesh (save once)
mean_mesh = trimesh.Trimesh(
    vertices=mean_vertices,
    faces=template_mesh.faces
)
mean_mesh.export(os.path.join(output_folder, "mean_shape.stl"))

for i in range(5):

    plus_vertices = (
        mean_shape +
        2 * sigma[i] * eigenvectors[i]
    ).reshape(-1, 3)

    minus_vertices = (
        mean_shape -
        2 * sigma[i] * eigenvectors[i]
    ).reshape(-1, 3)

    plus_mesh = trimesh.Trimesh(
        vertices=plus_vertices,
        faces=template_mesh.faces
    )

    minus_mesh = trimesh.Trimesh(
        vertices=minus_vertices,
        faces=template_mesh.faces
    )

    # Save with mode number
    plus_mesh.export(
        os.path.join(output_folder, f"mode{i+1}_plus_2sigma.stl")
    )

    minus_mesh.export(
        os.path.join(output_folder, f"mode{i+1}_minus_2sigma.stl")
    )

In [36]:
import numpy as np
import os

ssm_dir = "ssm_basis"
os.makedirs(ssm_dir, exist_ok=True)

# Persist exactly what you need to reconstruct any shape from any p-vector.
# Don't save sigma1..sigma5 as separate scalars — that's the same pattern
# that caused the bug. Save the full array, index into it.
np.save(os.path.join(ssm_dir, "mean_shape.npy"), mean_shape)          # flat, shape (219879,) or however you have it
np.save(os.path.join(ssm_dir, "eigenvectors.npy"), eigenvectors)      # shape (5, 219879)
np.save(os.path.join(ssm_dir, "sigma.npy"), sigma)                    # shape (5,)
np.save(os.path.join(ssm_dir, "faces.npy"), template_mesh.faces)      # shape (F, 3), constant topology

print("Saved:")
print("  mean_shape:", mean_shape.shape)
print("  eigenvectors:", eigenvectors.shape)
print("  sigma:", sigma.shape, sigma/100)
print("  faces:", template_mesh.faces.shape)

Saved:
  mean_shape: (236532,)
  eigenvectors: (5, 236532)
  sigma: (5,) [29.85029559 17.36660338  7.12843112  4.18808597  3.73086647]
  faces: (157684, 3)
