In [ ]:
import trimesh
import os

folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\DATASET\DATASET\50_FemurMeshes"

for i in range(1, 21):
    filename = f"femur_{i:02d}.stl"  # femur_01.stl, femur_02.stl, ...
    filepath = os.path.join(folder, filename)

    mesh = trimesh.load(filepath)

    print(f"\n{filename}")
    size = mesh.bounds[1] - mesh.bounds[0]
    print(mesh.bounds)
    print()
    print("difference =",size)
    print()
    print("vertices =",len(mesh.vertices))
    print("faces =",len(mesh.faces))
    print()


femur_01.stl
[[300.08782959 169.59111023 685.74206543]
 [388.52203369 255.89686584 847.6472168 ]]

difference = [ 88.4342041   86.30575562 161.90515137]

vertices= 22903
faces = 45666


femur_02.stl
[[277.52514648  91.5723114  740.65368652]
 [375.79940796 225.59112549 975.21337891]]

difference = [ 98.27426147 134.01881409 234.55969238]

vertices= 38588
faces = 77008


femur_03.stl
[[285.55282593  91.9970932  735.78637695]
 [372.18844604 174.8107605  890.14031982]]

difference = [ 86.63562012  82.8136673  154.35394287]

vertices= 24580
faces = 49012


femur_04.stl
[[298.64367676 146.63520813 703.17755127]
 [370.62915039 234.53712463 847.63122559]]

difference = [ 71.98547363  87.9019165  144.45367432]

vertices= 17871
faces = 35620


femur_05.stl
[[326.69155884 171.24700928 738.23059082]
 [419.51623535 284.77139282 917.66314697]]

difference = [ 92.82467651 113.52438354 179.43255615]

vertices= 25958
faces = 51772


femur_06.stl
[[328.56503296 150.00398254 795.68829346]
 [420.49395752

In [35]:
import trimesh

mesh4 = trimesh.load("femur_04.stl")
mesh10 = trimesh.load("femur_10.stl")
print("Volume of femur 4:", mesh4.volume,"\nVolume of femur 10:",mesh10.volume)
print("Surface Area of femur 4:", mesh4.area,"\nSurface Area of femur 10:",mesh10.area)

Volume of femur 4: 137693.84030244374 
Volume of femur 10: 362631.40748629515
Surface Area of femur 4: 18984.575045827914 
Surface Area of femur 10: 39503.72730532861


In [36]:
import os 
folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\DATASET\DATASET\50_FemurMeshes"

for i in range(1, 21):
    filename = f"femur_{i:02d}.stl"  # femur_01.stl, femur_02.stl, ...
    filepath = os.path.join(folder, filename)
    mesh = trimesh.load(filepath)
    print(mesh.is_watertight)    

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False


In [3]:
import json
import os

folder = r"C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data"

files = [
    "Center of femoral head_04.mrk.json",
    "Most inferior point of head_04.mrk.json",
    "Most superior point of head_04.mrk.json",
    "Tip of greater trochanter_04.mrk.json",
    "Lateral-most Tip_04.mrk.json",
    "Tip of lesser trochanter_04.mrk.json",
    "Posterior Shaft Edge_04.mrk.json",
    "Anterior Shaft Edge_04.mrk.json",
    "Lateral Shaft Edge_04.mrk.json",
    "Shaft Center at Cut Plane_04.mrk.json",
    "Neck center_04.mrk.json"
]

landmarks = {}

for file in files:
    filepath = os.path.join(folder, file)

    with open(filepath, "r") as f:
        data = json.load(f)

    point = data["markups"][0]["controlPoints"][0]["position"]

    name = os.path.basename(file).replace(".mrk.json", "")

    landmarks[name] = point

output_file = os.path.join(folder, "femur_04_landmarks.json")

with open(output_file, "w") as f:
    json.dump({"landmarks": landmarks}, f, indent=4)

print(f"Merged successfully: {output_file}")

Merged successfully: C:\Users\Yash\OneDrive\Desktop\Nit Internship\Base paper Implementation\Dataset\Experimental Data\femur_04_landmarks.json


In [11]:
import numpy as np

femur_04_landmarks = np.array([
    [314.631,182.628,723.2381896972656],  # head center
    [312.70159912109375,186.0531005859375,743.22265625],  # head inferior
    [316.5597839355469,179.20372009277344,703.2537231445312],  # head superior
    [358.05767822265625,153.5972900390625,736.7156372070312],  # greater trochanter
    [313.7513122558594,187.5194854736328,784.2379760742188]   # lesser trochanter
])

femur_10_landmarks = np.array([
    [325.574,166.354,747.2615966796875],  # head center
    [322.0124206542969,170.06590270996094,773.54296875],  # head inferior
    [329.1759033203125,162.64859008789062,720.9874877929688],  # head superior
    [388.9371337890625,140.082763671875,769.31494140625],  # greater trochanter
    [328.8636169433594,154.33778381347656,821.2492065429688]   # lesser trochanter
])

femur_16_landmarks = np.array([
    [321.078,240.71,681.9187927246094],  # head center
    [319.8430480957031,244.03097534179688,702.761962890625],  # head inferior
    [322.3133239746094,237.38804626464844,661.0756225585938],  # head superior
    [371.1664123535156,207.84083557128906,688.9606323242188],  # greater trochanter
    [333.8719177246094,232.47093200683594,742.3307495117188]   # lesser trochanter
])

print(femur_04_landmarks[0]-femur_10_landmarks[0])
print(femur_04_landmarks[1]-femur_10_landmarks[1])
print(femur_04_landmarks[2]-femur_10_landmarks[2])
print(femur_04_landmarks[3]-femur_10_landmarks[3])
print(femur_04_landmarks[4]-femur_10_landmarks[4])


[-10.943       16.274      -24.02340698]
[ -9.31082153  15.98719788 -30.3203125 ]
[-12.61611938  16.55513    -17.73376465]
[-30.87945557  13.51452637 -32.5993042 ]
[-15.11230469  33.18170166 -37.01123047]


In [17]:
#Euclidean Distance
import numpy as np
print("Difference between femur 04 and 10:")
for i in range(5):
    d = np.linalg.norm(
        femur_04_landmarks[i] - femur_10_landmarks[i]
    )
    print(f"Landmark {i+1}: {d:.2f} mm")
    
print()
print("Difference between femur 16 and 10:")

for i in range(5):
    d = np.linalg.norm(
        femur_16_landmarks[i] - femur_10_landmarks[i]
    )
    print(f"Landmark {i+1}: {d:.2f} mm")

Difference between femur 04 and 10:
Landmark 1: 31.01 mm
Landmark 2: 35.52 mm
Landmark 3: 27.34 mm
Landmark 4: 46.89 mm
Landmark 5: 51.95 mm

Difference between femur 16 and 10:
Landmark 1: 99.09 mm
Landmark 2: 102.40 mm
Landmark 3: 96.03 mm
Landmark 4: 106.60 mm
Landmark 5: 111.17 mm
